"""Schemas for the display_object_on_board tool wrapper."""

from __future__ import annotations

from pydantic import BaseModel, Field


class DisplayObjectOnBoardArgs(BaseModel):
    """Arguments generated by the model for display_object_on_board.

    Args:
        name: Object name to search and display.
    """

    name: str = Field(..., min_length=1)


class DisplayObjectOnBoardToolResult(BaseModel):
    """Tool wrapper result for board display and model feedback."""

    query: str
    image_url: str | None = None
    source_url: str | None = None
    title: str = ""
    elapsed_ms: float = 0.0
    error: str | None = None
    tool_response_content: dict[str, object] = Field(default_factory=dict)
